[package]
name = "hypercore"
version = "0.1.6-alpha.0"
license = "MIT OR Apache-2.0"
description = "Secure, distributed, append-only log"
documentation = "https://docs.rs/hypercore"
repository = "https://github.com/datrs/hypercore"
readme = "README.md"
authors = ["Yoshua Wuyts <yoshuawuyts@gmail.com>"]

[dependencies]
failure = "0.1.1"
lazy_static = "1.0.0"
rust_sodium = "0.8.0"
blake2-rfc = "0.2.18"
byteorder = "1.2.1"
merkle-tree-stream = "0.2.0"
flat-tree = "2.1.0"
sparse-bitfield = "0.2.0"
random-access-memory = "0.1.0"

[dev-dependencies]
clippy = "0.0"
