[package]
name = "hypercore"
version = "0.1.7"
license = "MIT OR Apache-2.0"
description = "Secure, distributed, append-only log"
documentation = "https://docs.rs/hypercore"
repository = "https://github.com/datrs/hypercore"
readme = "README.md"
authors = ["Yoshua Wuyts <yoshuawuyts@gmail.com>"]

[dependencies]
failure = "0.1.1"
lazy_static = "1.0.0"
blake2-rfc = "0.2.18"
byteorder = "1.2.2"
merkle-tree-stream = "0.3.0"
flat-tree = "3.3.0"
sparse-bitfield = "0.3.2"
random-access-memory = "0.2.0"
tree-index = "0.1.0"
memory-pager = "0.4.5"
sleep-parser = "0.4.0"
random-access-storage = "0.3.2"
random-access-disk = "0.3.0"
ed25519-dalek = "0.6.2"
sha2 = "0.7.1"
rand = "0.4.2"
pretty-hash = "0.2.0"

[dev-dependencies]
# clippy = "0.0"
