[package]
name = "hypercore"
version = "0.0.2"
license = "MIT OR Apache-2.0"
repository = "https://github.com/datrs/hypercore"
documentation = "https://docs.rs/hypercore"
description = "Secure, distributed, append-only log"
authors = ["Yoshua Wuyts <yoshuawuyts@gmail.com>"]

[dependencies]
failure = "0.1.1"
lazy_static = "1.0.0"
rust_sodium = "0.8.0"
blake2-rfc = "0.2.18"
byteorder = "1.2.1"
merkle-tree-stream = "0.1.1"

[dev-dependencies]
clippy = "0.0"
